### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by vitalickck** [life-live/megamarket-parser#3]
Приветствую!
Скачал парсер, добавил ссылку  сюда:
``def parse(driver, page: int):
    url = f"https://megamarket.ru/catalog/?q=lays"``
но выдает ошибку:
`Traceback (most recent call last):
  File "C:\Users\spz\Desktop\megamarket-parser-main\megamarket-parser-main\main.py", line 135, in <module>
    main()
  File "C:\Users\spz\Desktop\megamarket-parser-main\megamarket-parser-main\main.py", line 90, in main
    driver = uc.Chrome(options=options)
  File "C:\Users\spz\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 258, in __init__
    self.patcher.auto()
  File "C:\Users\spz\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\patcher.py", line 178, in auto
    self.unzip_package(self.fetch_package())
  File "C:\Users\spz\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\patcher.py", line 287, in fetch_package
    return urlretrieve(download_url)[0]
  File "C:\Users\spz\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\spz\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\spz\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\spz\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\spz\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Users\spz\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\spz\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found`

Подскажите, пожалуйста, в чём ошибка и что делать? Куки не трогал и ничего с ними не делал.

**Comment by life-live** [comment]
Привет, вообще нужно не так указывать ссылку. 
Щас сделаю и выложу новую версию, с более простым указанием ссылки

**Comment by life-live** [comment]
Привет, поиск по запросу не получится сделать. Только по каталогу и ты не правильно настроил вообще, ссылку не надо указывать в коде, работа через config. 
![image](https://github.com/life-live/megamarket-parser/assets/96289868/e65b9a19-656d-4164-a91b-4739eaa5c255)

В вашем случае catalog - chipsy
После парсинга все сохранится в Excel файл, там уже вы можете и только чипсы Lays собрать, согласен, что по скорости не очень, но зато соберет больше единиц товаров Lays, чем по запросу в поиске
![image](https://github.com/life-live/megamarket-parser/assets/96289868/1274d324-17ff-407a-b885-671953c65fdf)

**Comment by life-live** [comment]
А код ты обратно изменил-то?
![image](https://github.com/life-live/megamarket-parser/assets/96289868/19fc41d3-e51a-4aa5-b87d-980f40736bc3)

**Comment by vitalickck** [comment]
Я скачал код из репозитория заново и ничего туда не добавлял.

`Traceback (most recent call last):
  File "C:\Users\Виталий\Desktop\megamarket-parser-main\megamarket-parser-main\main.py", line 135, in <module>
    main()
  File "C:\Users\Виталий\Desktop\megamarket-parser-main\megamarket-parser-main\main.py", line 90, in main
    driver = uc.Chrome(options=options)
  File "C:\Users\Виталий\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "C:\Users\Виталий\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\Виталий\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "C:\Users\Виталий\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "C:\Users\Виталий\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "C:\Users\Виталий\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "C:\Users\Виталий\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Виталий\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:51027
from session not created: This version of ChromeDriver only supports Chrome version 125
Current browser version is 124.0.6367.209
Stacktrace:
	GetHandleVerifier [0x00FAB793+45827]
	(No symbol) [0x00F3DB74]
	(No symbol) [0x00E3150F]
	(No symbol) [0x00E63FDA]
	(No symbol) [0x00E633CD]
	(No symbol) [0x00E5A420]
	(No symbol) [0x00E5A267]
	(No symbol) [0x00E9C9A2]
	(No symbol) [0x00E9C1CA]
	(No symbol) [0x00E92B96]
	(No symbol) [0x00E66998]
	(No symbol) [0x00E6751D]
	GetHandleVerifier [0x012643C3+2899763]
	GetHandleVerifier [0x012B77ED+3240797]
	GetHandleVerifier [0x01031264+593364]
	GetHandleVerifier [0x0103818C+621820]
	(No symbol) [0x00F46F54]
	(No symbol) [0x00F43658]
	(No symbol) [0x00F437F7]
	(No symbol) [0x00F358AE]
	BaseThreadInitThunk [0x75F5FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77237B1E+286]
	RtlGetAppContainerNamedObjectPath [0x77237AEE+238]

`

**Comment by life-live** [comment]
У тебя Chrome скачен?

**Comment by vitalickck** [comment]
Конечно скачан. Им и пользуюсь.
